In [341]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
import tensorflow

In [342]:
yxdf = pd.read_csv('Churn_Modelling.csv')

In [343]:
yxdf

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [344]:
xdf = pd.get_dummies(yxdf,columns=['Geography','Gender'],drop_first=True)


In [345]:
xdf

RowNumber  CustomerId    Surname  CreditScore  Age  Tenure    Balance  \
0             1    15634602   Hargrave          619   42       2       0.00   
1             2    15647311       Hill          608   41       1   83807.86   
2             3    15619304       Onio          502   42       8  159660.80   
3             4    15701354       Boni          699   39       1       0.00   
4             5    15737888   Mitchell          850   43       2  125510.82   
...         ...         ...        ...          ...  ...     ...        ...   
9995       9996    15606229   Obijiaku          771   39       5       0.00   
9996       9997    15569892  Johnstone          516   35      10   57369.61   
9997       9998    15584532        Liu          709   36       7       0.00   
9998       9999    15682355  Sabbatini          772   42       3   75075.31   
9999      10000    15628319     Walker          792   28       4  130142.79   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0                 1          1               1        101348.88       1   
1                 1          0               1        112542.58       0   
2                 3          1               0        113931.57       1   
3                 2          0               0         93826.63       0   
4                 1          1               1         79084.10       0   
...             ...        ...             ...              ...     ...   
9995              2          1               0         96270.64       0   
9996              1          1               1        101699.77       0   
9997              1          0               1         42085.58       1   
9998              2          1               0         92888.52       1   
9999              1          1               0         38190.78       0   

      Geography_Germany  Geography_Spain  Gender_Male  
0                 False            False        False  
1                 False             True        False  
2                 False            False        False  
3                 False            False        False  
4                 False             True        False  
...                 ...              ...          ...  
9995              False            False         True  
9996              False            False         True  
9997              False            False        False  
9998               True            False         True  
9999              False            False        False  

[10000 rows x 15 columns]

In [346]:
xdf[['Geography_Germany', 'Geography_Spain', 'Gender_Male']] = xdf[['Geography_Germany', 'Geography_Spain','Gender_Male']].astype(int)


In [347]:
from sklearn.model_selection import train_test_split

In [348]:
df = xdf.drop(columns=['Surname'])
df = xdf.drop(columns=['RowNumber','CustomerId'])


In [349]:
x = df.drop(columns=['Exited'])
y = df['Exited']
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [350]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=3)

In [351]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [352]:
x_test

Surname  CreditScore  Age  Tenure    Balance  NumOfProducts  \
5876  Humphries          704   39       2  111525.02              1   
6555      Bales          641   35       5       0.00              2   
1448     Diribe          555   46       4  120392.99              1   
3351    Holland          474   34       9  176311.36              1   
231     Freeman          610   40       0       0.00              2   
...         ...          ...  ...     ...        ...            ...   
869        Page          435   36       4       0.00              1   
2928    Jenkins          668   39       0  122104.79              1   
8436    Nwankwo          834   40       7       0.00              2   
6312      Green          658   28       9  152812.58              1   
7195   Santiago          675   33       6       0.00              2   

      HasCrCard  IsActiveMember  EstimatedSalary  Geography_Germany  \
5876          1               0        199484.96                  0   
6555          1               0         93148.93                  0   
1448          1               0        177719.88                  1   
3351          1               0        160213.27                  1   
231           1               0         62232.60                  0   
...         ...             ...              ...                ...   
869           1               1        197015.20                  0   
2928          1               0        112946.67                  1   
8436          0               0         45038.74                  0   
6312          1               0        166682.57                  1   
7195          1               0         34045.61                  0   

      Geography_Spain  Gender_Male  
5876                0            1  
6555                0            1  
1448                0            0  
3351                0            0  
231                 0            1  
...               ...          ...  
869                 0            1  
2928                0            0  
8436                1            1  
6312                0            0  
7195                0            0  

[2000 rows x 12 columns]

In [353]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8000 entries, 5291 to 5994
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Surname            8000 non-null   object 
 1   CreditScore        8000 non-null   int64  
 2   Age                8000 non-null   int64  
 3   Tenure             8000 non-null   int64  
 4   Balance            8000 non-null   float64
 5   NumOfProducts      8000 non-null   int64  
 6   HasCrCard          8000 non-null   int64  
 7   IsActiveMember     8000 non-null   int64  
 8   EstimatedSalary    8000 non-null   float64
 9   Geography_Germany  8000 non-null   int64  
 10  Geography_Spain    8000 non-null   int64  
 11  Gender_Male        8000 non-null   int64  
dtypes: float64(2), int64(9), object(1)
memory usage: 812.5+ KB


In [354]:
x_test = x_test.drop(columns=['Surname'])

In [355]:
x_train = x_train.drop(columns=['Surname'])

In [356]:
X_train = scaler.fit_transform(x_train)
X_test = scaler.fit_transform(x_test)

In [357]:
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [358]:
X_train

array([[ 0.0862834 , -0.6601382 , -1.0446036 , ..., -0.58023704,
        -0.57542576, -1.09499335],
       [ 0.31430986, -0.75549256, -0.35146473, ...,  1.72343359,
        -0.57542576,  0.91324755],
       [-1.82084701,  0.57946842, -1.73774248, ..., -0.58023704,
        -0.57542576, -1.09499335],
       ...,
       [ 0.28321534,  1.53301197, -0.35146473, ...,  1.72343359,
        -0.57542576,  0.91324755],
       [-0.51487727,  0.198051  , -1.39117304, ..., -0.58023704,
        -0.57542576, -1.09499335],
       [-0.7325389 , -0.37407514,  1.72795189, ...,  1.72343359,
        -0.57542576,  0.91324755]])

In [359]:
model = Sequential()
model.add(Dense(10,activation='sigmoid',input_dim = 11))
model.add(Dense(5,activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))


c:\Users\Ayush Maurya\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [360]:
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_34 (Dense)                │ (None, 10)             │           120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 5)              │            55 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_36 (Dense)                │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 181 (724.00 B)

 Trainable params: 181 (724.00 B)

 Non-trainable params: 0 (0.00 B)

In [361]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [362]:
print(X_train.shape)


(8000, 11)


In [363]:
model.fit(X_train,y_train,epochs = 15)

Epoch 1/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.5801
Epoch 2/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4924
Epoch 3/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4861
Epoch 4/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4654
Epoch 5/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4554
Epoch 6/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4429
Epoch 7/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4329
Epoch 8/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4304
Epoch 9/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4224
Epoch 10/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4295
Epoch 11/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4284
Epoch 12/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4111
Epoch 13/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4098
Epoch 14/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4168
Epoch 15/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - lo

In [364]:
model.layers[2].get_weights()

[array([[-1.1734204],
        [ 1.2926098],
        [-0.4044135],
        [-1.2688403],
        [ 0.744072 ]], dtype=float32),
 array([-0.21308467], dtype=float32)]

In [365]:
y_log = model.predict(x_test)
y_log

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step  


array([[0.26807508],
       [0.1085917 ],
       [0.26807508],
       ...,
       [0.1085917 ],
       [0.4213858 ],
       [0.1085917 ]], dtype=float32)

In [366]:
y_prd = np.where(y_log>0.5,1,0)

In [367]:
y_prd

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [373]:
y_test

5876    0
6555    0
1448    1
3351    0
231     0
       ..
869     0
2928    1
8436    0
6312    0
7195    0
Name: Exited, Length: 2000, dtype: int64

In [368]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_prd)

0.8025

In [369]:
from sklearn.ensemble import RandomForestClassifier
modelx = RandomForestClassifier()

In [370]:
modelx.fit(x_train,y_train)

RandomForestClassifier()

In [371]:
preds = modelx.predict(x_test)

In [372]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,preds)

0.8645

In [377]:

import pandas as pd

# Create a DataFrame with 2000 rows and 1 column filled with zeros
df = pd.DataFrame(0, index=range(2000), columns=["Column1"])

# Display the result (optional)
for idx, value in df.iterrows():
    print(f"Row {idx}: {value['Column1']}")


Row 0: 0
Row 1: 0
Row 2: 0
Row 3: 0
Row 4: 0
Row 5: 0
Row 6: 0
Row 7: 0
Row 8: 0
Row 9: 0
Row 10: 0
Row 11: 0
Row 12: 0
Row 13: 0
Row 14: 0
Row 15: 0
Row 16: 0
Row 17: 0
Row 18: 0
Row 19: 0
Row 20: 0
Row 21: 0
Row 22: 0
Row 23: 0
Row 24: 0
Row 25: 0
Row 26: 0
Row 27: 0
Row 28: 0
Row 29: 0
Row 30: 0
Row 31: 0
Row 32: 0
Row 33: 0
Row 34: 0
Row 35: 0
Row 36: 0
Row 37: 0
Row 38: 0
Row 39: 0
Row 40: 0
Row 41: 0
Row 42: 0
Row 43: 0
Row 44: 0
Row 45: 0
Row 46: 0
Row 47: 0
Row 48: 0
Row 49: 0
Row 50: 0
Row 51: 0
Row 52: 0
Row 53: 0
Row 54: 0
Row 55: 0
Row 56: 0
Row 57: 0
Row 58: 0
Row 59: 0
Row 60: 0
Row 61: 0
Row 62: 0
Row 63: 0
Row 64: 0
Row 65: 0
Row 66: 0
Row 67: 0
Row 68: 0
Row 69: 0
Row 70: 0
Row 71: 0
Row 72: 0
Row 73: 0
Row 74: 0
Row 75: 0
Row 76: 0
Row 77: 0
Row 78: 0
Row 79: 0
Row 80: 0
Row 81: 0
Row 82: 0
Row 83: 0
Row 84: 0
Row 85: 0
Row 86: 0
Row 87: 0
Row 88: 0
Row 89: 0
Row 90: 0
Row 91: 0
Row 92: 0
Row 93: 0
Row 94: 0
Row 95: 0
Row 96: 0
Row 97: 0
Row 98: 0
Row 99: 0
Row 100: 0